version: '3.9'

services:
  api:
    container_name: bidcom-api
    build: .
    ports:
      - '8000:8000'
    environment:
      - PORT=8000
      - DATABASE_URL=db.sqlite
    volumes:
      - ./db.sqlite:/app/db.sqlite